apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beecowgateway-app
  name: beecowgateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beecowgateway-app
  strategy: {}
  template:
    metadata:
      labels:
        app: beecowgateway-app
    spec:
      containers:
      - image: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/gateway-dev:V.1.0.1
        name: beecowgateway
        ports:
        - containerPort: 8080
        - containerPort: 8859
        - containerPort: 8848
        resources:
          limits:
            cpu: '1'
          requests:
            cpu: '0.4'
        livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 600
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        env: 
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@jhipster-registry.default.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.46:5432/postgres?currentSchema=gateway-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD 
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "5"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xmx2048m -Xms256m"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: beecowgateway-app
  name: beecowgateway-app
spec:
  ports:
  - name: tcp-9090
    port: 9090
    protocol: TCP
    targetPort: 8080
  - name: tcp-8848
    port: 8848
    protocol: TCP
    targetPort: 8848
  - name: tcp-8849
    port: 8849
    protocol: TCP
    targetPort: 8849
  selector:
    app: beecowgateway-app
status:
  loadBalancer: {}
