apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: intergrate-affiliate-service
  name: intergrate-affiliate-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: intergrate-affiliate-service
  strategy: {}
  template:
    metadata:
      labels:
        app: intergrate-affiliate-service
    spec:
      containers:
      - image: intergrate-affiliate-service
        name: intergrate-affiliate-service
        ports:
        - name: service
          containerPort: 8087
          protocol: TCP
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          httpGet:
            path: /management/health
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.48:5432/postgres?currentSchema=affiliate-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "r57c3XpCDMGQ"
          - name: JHIPSTER_SLEEP
            value: "5"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G -Dhttp.agent=curl/7.55.1"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
