apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: intergrate-affiliate-service
  name: intergrate-affiliate-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: intergrate-affiliate-service
  strategy: {}
  template:
    metadata:
      labels:
        app: intergrate-affiliate-service
    spec:
      containers:
      - image: intergrate-affiliate-service
        name: intergrate-affiliate-service
        ports:
        - name: service
          containerPort: 8087
          protocol: TCP
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          httpGet:
            path: /management/health
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: intergrate-affiliate-service
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
