apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mail-services
  name: mail-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-services
  strategy: {}
  template:
    metadata:
      labels:
        app: mail-services
    spec:
      containers:
      - image: mail-services
        name: mail-services
        ports:
        - name: service
          containerPort: 8180
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            # cpu: '1'
            memory: 2Gi
          requests:
            # cpu: '0.2'
            memory: 1Gi

        livenessProbe:
          tcpSocket:
            port: 8180
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8180
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: mail-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
