apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: billing-info-services
  name: billing-info-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-info-services
  strategy: {}
  template:
    metadata:
      labels:
        app: billing-info-services
    spec:
      containers:
      - image: billing-info-services
        name: billing-info-services
        ports:
        - name: service
          containerPort: 8405
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            cpu: '1'
            memory: 4Gi 
          requests:
            cpu: '0.2'
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8405
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8405
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.48:5432/postgres?currentSchema=billing-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
