apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sms-services
  name: sms-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-services
  strategy: {}
  template:
    metadata:
      labels:
        app: sms-services
    spec:
      containers:
      - image: sms-services
        name: sms-services
        ports:
        - name: service
          containerPort: 8401
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            # cpu: '0.5'
            memory: 1Gi
          requests:
            # cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          tcpSocket:
            port: 8401
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8401
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: sms-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
