apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-registry
spec:
  template:
    spec:
      containers:
      - name: jhipster-registry
        env:
        - name: DEBUG
          value: "true"