apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: integrate-order-service
  name: integrate-order-service
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrate-order-service
  strategy: {}
  template:
    metadata:
      labels:
        app: integrate-order-service
    spec:
      containers:
      - image: integrate-order-service
        name: integrate-order-service
        ports:
        - name: service
          containerPort: 8085
          protocol: TCP
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          httpGet:
            path: /management/health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: integrate-order-service
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
