apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: integrateorderitemservice
  name: integrateorderitemservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integrateorderitemservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: integrateorderitemservice
    spec:
      containers:
      - image: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/integrate-order-itemservice-dev:V.1.0.1
        name: integrate-order-itemservice-dev
        ports:
        - name: service
          containerPort: 8085
          protocol: TCP
        resources: {}
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@jhipster-registry.default.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.46:5432/postgres?currentSchema=order-services2"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "5"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G -Dhttp.agent=curl/7.55.1"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
