apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ca-
namespace: ca

images:
- name: mail-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/ca-mail-services
  newTag:               2023.08.02.3

resources:
- ../../../gosell/31.mail-services

labels:
- includeSelectors: true
  pairs:
    env: ca

replicas:
- name: mail-services
  count: 1
