apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssrstorefront-services
  name: ssrstorefront-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssrstorefront-services
  strategy: {}
  template:
    metadata:
      labels:
        app: ssrstorefront-services
    spec:
      containers:
      - image: ssrstorefront-services
        name: ssrstorefront-services
        ports:
          - name: service
            containerPort: 8286
            protocol: TCP
          - name: hazale
            containerPort: 5701
            protocol: UDP
        resources:
          limits:
            cpu: '3'
            memory: 4Gi
          requests:
            cpu: 1
            memory: 3Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8286
            scheme: HTTP
          initialDelaySeconds: 300
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8286
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sleep
                - '5'
        envFrom:
          - secretRef:
              name: ssrstorefront-services
      imagePullSecrets:
        - name: fpt-cloud-registry  
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssrstorefront-services
  name: ssrstorefront-services
spec:
  ports:
  - name: tcp-8286
    port: 8286
    protocol: TCP
    targetPort: 8286

  selector:
    app: ssrstorefront-services
status:
  loadBalancer: {}
