apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssrstorefront-services
  name: ssrstorefront-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssrstorefront-services
  strategy: {}
  template:
    metadata:
      labels:
        app: ssrstorefront-services
    spec:
      containers:
      - image: ssrstorefront-services
        name: ssrstorefront-services
        ports:
          - name: service
            containerPort: 8286
            protocol: TCP
          - name: hazale
            containerPort: 5701
            protocol: UDP
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 3Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8286
            scheme: HTTP
          initialDelaySeconds: 300
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8286
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sleep
                - '5'
        env: 
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.48:5432/postgres?currentSchema=ssrstorefront-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "10"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry  
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssrstorefront-services
  name: ssrstorefront-services
spec:
  ports:
  - name: tcp-8286
    port: 8286
    protocol: TCP
    targetPort: 8286

  selector:
    app: ssrstorefront-services
status:
  loadBalancer: {}
