apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: itemetl-load-services
  name: itemetl-load-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itemetl-load-services
  strategy: {}
  template:
    metadata:
      labels:
        app: itemetl-load-services
    spec:
      containers:
      - image: itemetl-load-services
        name: itemetl-load-services
        ports:
        - containerPort: 8086
        resources: 
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.2'
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8086
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8086
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom: 
          - secretRef:
              name: itemetl-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: itemetl-load-services
  name: itemetl-load-services
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: itemetl-load-services
status:
  loadBalancer: {}
