apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lazada-services
  name: lazada-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: lazada-services
  strategy: {}
  template:
    metadata:
      labels:
        app: lazada-services
    spec:
      containers:
      - image: lazada-services
        name: lazada-services
        ports:
        - name: service
          containerPort: 8081
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8082
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.48:5432/postgres?currentSchema=lazada-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "r57c3XpCDMGQ"
          - name: JHIPSTER_SLEEP
            value: "10"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
