apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

images:
- name: jhipster-registry
  newTag: v3.1.2

resources:
- ../../../gosell/1.jhipster-registry

labels:
- includeSelectors: true
  pairs:
    env: dev

replicas:
  - name: registry
    count: 1
