apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

images:
- name: jhipster-registry
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/dev-registry
  newTag:  2023.05.11.10

resources:
- ../../../gosell/1.jhipster-registry

labels:
- includeSelectors: true
  pairs:
    env: dev

replicas:
  - name: registry
    count: 1
