apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalog-services
  name: catalog-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-services
  strategy: {}
  template:
    metadata:
      labels:
        app: catalog-services
    spec:
      containers:
      - image: catalog-services
        name: catalog-services
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.2'
            memory: 200Mi
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: catalog-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: catalog-services
  name: catalog-services
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: catalog-services
status:
  loadBalancer: {}
