apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ca-
namespace: ca

images:
- name: wallet-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/ca-new-wallet-services
  newTag:                                                  2023.10.31.7

resources:
- ../../../gosell/wallet-services

labels:
- includeSelectors: true
  pairs:
    env: ca

replicas:
- name: wallet-services
  count: 1

