apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ca-
namespace: ca

images:
- name: media-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/ca-new-media-services
  newTag:                               2023.12.29.21

resources:
- ../../../gosell/6.media-services
labels:
- includeSelectors: true
  pairs:
    env: ca

replicas:
- name: media-services
  count: 1

