apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopee-services
  name: shopee-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopee-services
  strategy: {}
  template:
    metadata:
      labels:
        app: shopee-services
    spec:
      containers:
      - image: shopee-services
        name: shopee-services
        ports:
        - name: service
          containerPort: 8406
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            # cpu: '0.5'
            memory: 1Gi
          requests:
            # cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          httpGet:
            path: /management/health
            port: 8406
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8406
            scheme: HTTP
        envFrom:
          - secretRef:
              name: shopee-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
