apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-services
  name: payment-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-services
  strategy: {}
  template:
    metadata:
      labels:
        app: payment-services
    spec:
      containers:
      - image: payment-services
        name: payment-services
        ports:
        - name: service
          containerPort: 9004
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          tcpSocket:
            port: 9004
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9004
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: payment-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
