apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service2
  name: order-service2
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service2
  strategy: {}
  template:
    metadata:
      labels:
        app: order-service2
    spec:
      containers:
      - image: order-service2
        name: order-service2
        ports:
        - name: service
          containerPort: 8404
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            cpu: '1'
            memory: 3584Mi
          requests:
            cpu: '0.2'
            memory: 2Gi
        livenessProbe:
          tcpSocket:
            port: 8404
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8404
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.10.85:5432/postgres?currentSchema=order-services2"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "5"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G -Dhttp.agent=curl/7.55.1"
          - name: GHN_API_URL
            value: "https://dev-online-gateway.ghn.vn"
          - name: GHN_API_TOKEN
            value: "30b4aba8-ee84-11ea-8ad2-56f8530407f0"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
