
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

images:
- name: catalog-services
newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/dev-catalog-services
newTag: 2023.04.29.1

resources:
- ../../../gosell/3.catalogservice
labels:
- includeSelectors: true
pairs:
    env: dev

replicas:
- name: catalog-services
    count: 10

