apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

images:
- name: item-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/dev-item-services
  newTag:      2023.05.06.14

resources:
- ../../../gosell/4.item-services
labels:
- includeSelectors: true
  pairs:
    env: dev

replicas:
- name: item-services
  count: 1

