apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zalo-services
  name: zalo-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: zalo-services
  strategy: {}
  template:
    metadata:
      labels:
        app: zalo-services
    spec:
      containers:
      - image: zalo-services
        name: zalo-services
        ports:
        - name: service
          containerPort: 8288
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          tcpSocket:
            port: 8288
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8288
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: zalo-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
