apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: callcenter-services
  name: callcenter-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: callcenter-services
  strategy: {}
  template:
    metadata:
      labels:
        app: callcenter-services
    spec:
      containers:
      - image: callcenter-services
        name: callcenter-services
        ports:
          - name: service
            containerPort: 8083
            protocol: TCP
          - name: hazale
            containerPort: 5701
            protocol: UDP
        resources: {}
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8083
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8083
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@jhipster-registry.default.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.46:5432/postgres?currentSchema=call-center-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "10"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
