apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: store-services
  name: store-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-services
  strategy: {}
  template:
    metadata:
      labels:
        app: store-services
    spec:
      containers:
      - image: store-services
        name: store-services
        ports:
        - name: service
          containerPort: 8586
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            # cpu: '1'
            memory: 1Gi
          requests:
            # cpu: '0.2'
            memory: 200Mi
        livenessProbe:
          tcpSocket:
            port: 8586
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8586
          initialDelaySeconds: 120
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: store-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
