apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: media-services
  name: media-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-services
  strategy: {}
  template:
    metadata:
      labels:
        app: media-services
    spec:
      containers:
      - image: media-services
        name: media-services
        ports:
        - name: service
          containerPort: 8990
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            cpu: '0.5'
          requests:
            cpu: '0.2'
        livenessProbe:
          tcpSocket:
            port: 8990
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8990
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.10.85:5432/postgres?currentSchema=media-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "3"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}

---
