apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ca-
namespace: ca

images:
- name: zalo-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/ca-zalo-services
  newTag:                 2023.08.02.1

resources:
- ../../../gosell/27.zalo-services

labels:
- includeSelectors: true
  pairs:
    env: ca

replicas:
- name: zalo-services
  count: 1
