apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: item-services
  name: item-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-services
  strategy: {}
  template:
    metadata:
      labels:
        app: item-services
    spec:
      containers:
      - image: item-services
        name: item-services
        ports:
        - containerPort: 8889
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.2'
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8889
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8889
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env: 
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@ca-registry.ca.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.33:5432/postgres?ApplicationName=itemServices&currentSchema=item-services"
          - name: POSTGRES_USER
            value: "dbaitem"
          - name: POSTGRES_PASSWORD
            value: "dbaitem"
          - name: JHIPSTER_SLEEP
            value: "10"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.23:9300"
          - name: "JAVA_OPTS"
            value: "-Xms256M -Xmx1G -Dhttp.agent=curl/7.55.1"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: item-services
  name: item-services
spec:
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app: item-services
status:
  loadBalancer: {}
