apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssr-store-front
  name: ssr-store-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssr-store-front
  strategy: {}
  template:
    metadata:
      labels:
        app: ssr-store-front
    spec:
      containers:
      - image: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/ssr-store-front-dev:V.1.0.1
        name: ssr-store-front-dev
        ports:
          - name: service
            containerPort: 8286
            protocol: TCP
          - name: hazale
            containerPort: 5701
            protocol: UDP
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 3Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8286
            scheme: HTTP
          initialDelaySeconds: 300
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8286
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sleep
                - '5'
        env: 
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@jhipster-registry.default.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.46:5432/postgres?currentSchema=ssrstorefront-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "10"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry  
status: {}
---
