apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ca-
namespace: ca

images:
- name: sms-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/ca-new-sms-services
  newTag:                       2023.09.26.7

resources:
- ../../../gosell/17.sms-services

labels:
- includeSelectors: true
  pairs:
    env: ca

replicas:
- name: sms-services
  count: 1


