apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ca-
namespace: ca

images:
- name: affiliate-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/ca-new-affiliate-services
  newTag:                                                                             2023.10.31.34

resources:
- ../../../gosell/32.affiliate-services

labels:
- includeSelectors: true
  pairs:
    env: ca

replicas:
- name: affiliate-services
  count: 1
