apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

images:
- name: sms-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/dev-sms-services
  newTag:        2023.05.01.4

resources:
- ../../../gosell/17.sms-services

labels:
- includeSelectors: true
  pairs:
    env: dev

replicas:
- name: sms-services
  count: 2


