apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-services
  name: inventory-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-services
  strategy: {}
  template:
    metadata:
      labels:
        app: inventory-services
    spec:
      containers:
      - image: inventory-services
        name: inventory-services
        ports:
        - name: service
          containerPort: 8083
          protocol: TCP
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8082
            scheme: HTTP
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.10.85:5432/postgres?currentSchema=inventory-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "5"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---

