apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-services
  name: inventory-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-services
  strategy: {}
  template:
    metadata:
      labels:
        app: inventory-services
    spec:
      containers:
      - image: inventory-services
        name: inventory-services
        ports:
        - name: service
          containerPort: 8083
          protocol: TCP
        resources:
          limits:
            # cpu: '1'
            memory: 2Gi
          requests:
            # cpu: '0.2'
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8082
            scheme: HTTP
        envFrom:
          - secretRef:
              name: inventory-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---

