apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: affiliate-services
    tags.datadoghq.com/env: "gosell-ca-new"
    tags.datadoghq.com/service: "affiliate"
    tags.datadoghq.com/version: ""
  name: affiliate-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: affiliate-services
  strategy: {}
  template:
    metadata:
      labels:
        app: affiliate-services
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.19.1
    spec:
      containers:
      - image: affiliate-services
        name: affiliate-services
        ports:
          - name: service
            containerPort: 8087
            protocol: TCP
          - name: hazale
            containerPort: 5701
            protocol: UDP
        resources: {}
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: affiliate-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---

