apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-services
  name: user-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-services
  template:
    metadata:
      labels:
        app: user-services
    spec:
      containers:
      - image: user-services
        name: user-services
        ports:
        - name: service
          containerPort: 8200
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources:
          limits:
            cpu: '1'
            memory: 3Gi
          requests:
            cpu: '0.2'
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 8200
          initialDelaySeconds: 200
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8200
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: user-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}

---
