apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-services
  name: user-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-services
  template:
    metadata:
      labels:
        app: user-services
    spec:
      containers:
      - image: user-services
        name: user-services
        ports:
        - name: service
          containerPort: 8200
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources: {}
        livenessProbe:
          tcpSocket:
            port: 8200
          initialDelaySeconds: 200
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8200
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.10.85:5432/postgres?currentSchema=user-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "3"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}

---
