apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

images:
- name: media-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/dev-media-services
  newTag: 2023.04.29.4

resources:
- ../../../gosell/6.media-services
labels:
- includeSelectors: true
  pairs:
    env: dev

replicas:
- name: media-services
  count: 10

