apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beehive-services
  name: beehive-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: beehive-services
  strategy: {}
  template:
    metadata:
      labels:
        app: beehive-services
    spec:
      containers:
      - image: beehive-services
        name: beehive-services
        ports:
        - name: service
          containerPort: 8081
          protocol: TCP
        resources: 
          limits:
            cpu: '1'
            memory: 4Gi
          requests:
            cpu: '0.2'
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /management/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 200
          timeoutSeconds: 2
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /management/health
            port: 8081
            scheme: HTTP
        envFrom:
          - secretRef:
              name: beehive-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
