apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cash-book-service
  name: cash-book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cash-book-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cash-book-service
    spec:
      containers:
      - image: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/cash-book-service:V.1.0.1
        name: cash-book-service
        ports:
        - name: service
          containerPort: 8284
          protocol: TCP
        resources: {}
        livenessProbe:
          tcpSocket:
            port: 8284
          initialDelaySeconds: 600
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8284
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env: 
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@jhipster-registry.default.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.111.46:5432/postgres?currentSchema=cashbook-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "10"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.8:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
