apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-
namespace: dev

images:
- name: itemetl-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/dev-itemetl-services
  newTag:       2023.05.06.13

resources:
- ../../../gosell/5.itemetl-services
labels:
- includeSelectors: true
  pairs:
    env: dev

replicas:
- name: itemetl-services
  count: 1
