apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theme-services
  name: theme-services
  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: theme-services
  strategy: {}
  template:
    metadata:
      labels:
        app: theme-services
    spec:
      containers:
      - image: theme-services
        name: theme-services
        ports:
          - name: service
            containerPort: 8282
            protocol: TCP
          - name: hazale
            containerPort: 5701
            protocol: UDP
        resources:
          limits:
            # cpu: '0.5'
            memory: 1Gi
          requests:
            # cpu: '0.2'
            memory: 200Mi

        livenessProbe:
          tcpSocket:
            port: 8282
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8282
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - secretRef:
              name: theme-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
