apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theme-services
  name: theme-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theme-services
  strategy: {}
  template:
    metadata:
      labels:
        app: theme-services
    spec:
      containers:
      - image: theme-services
        name: theme-services
        ports:
          - name: service
            containerPort: 8282
            protocol: TCP
          - name: hazale
            containerPort: 5701
            protocol: UDP
        resources: {}
        livenessProbe:
          tcpSocket:
            port: 8282
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8282
          initialDelaySeconds: 120
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prod,swagger"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://admin:admin@dev-registry.dev.svc.cluster.local:8761/config"
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://172.16.10.85:5432/postgres?currentSchema=theme-services"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: JHIPSTER_SLEEP
            value: "10"
          - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
            value: "172.16.111.46:9300"
          - name: JAVA_OPTS
            value: "-Xms256M -Xmx1G"
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
