apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ca-
namespace: ca

images:
- name: cashbook-services
  newName: registry.fke.fptcloud.com/81afa4a1-02f9-4191-8f77-1a07e8686f7a/ca-new-cashbook-services
  newTag:                     2023.08.24.4

resources:
- ../../../gosell/33.cashbook-services

labels:
- includeSelectors: true
  pairs:
    env: ca

replicas:
- name: cashbook-services
  count: 1
