apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tiki-services
  name: tiki-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiki-services
  strategy: {}
  template:
    metadata:
      labels:
        app: tiki-services
    spec:
      containers:
      - image: tiki-services
        name: tiki-services
        ports:
        - name: service
          containerPort: 8289
          protocol: TCP
        - name: hazale
          containerPort: 5701
          protocol: UDP
        resources: {}
        envFrom:
          - secretRef:
              name: tiki-services
      imagePullSecrets:
        - name: fpt-cloud-registry
status: {}
---
